demo-models/config/routes.rb
Rails.application.routes.draw do
  resources :my_names
  resources :my_totals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

demo-models/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo-models/app/models/my_name.rb
class MyName < ApplicationRecord

    validates :name, :length => { :minimum => 2, :maximum => 5}

    def name_and_surname 
        self.name + " " + self.surname
    end

end

demo-models/app/models/my_total.rb
class MyTotal < ApplicationRecord

    before_save :get_total

    def get_total
        self.total = self.first_operator + self.second_operator
    end

end

demo-models/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

demo-models/app/controllers/my_names_controller.rb
class MyNamesController < ApplicationController
  before_action :set_my_name, only: %i[ show edit update destroy ]

  # GET /my_names or /my_names.json
  def index
    @my_names = MyName.all
  end

  # GET /my_names/1 or /my_names/1.json
  def show
  end

  # GET /my_names/new
  def new
    @my_name = MyName.new
  end

  # GET /my_names/1/edit
  def edit
  end

  # POST /my_names or /my_names.json
  def create
    @my_name = MyName.new(my_name_params)

    respond_to do |format|
      if @my_name.save
        format.html { redirect_to @my_name, notice: "My name was successfully created." }
        format.json { render :show, status: :created, location: @my_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_names/1 or /my_names/1.json
  def update
    respond_to do |format|
      if @my_name.update(my_name_params)
        format.html { redirect_to @my_name, notice: "My name was successfully updated." }
        format.json { render :show, status: :ok, location: @my_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_names/1 or /my_names/1.json
  def destroy
    @my_name.destroy
    respond_to do |format|
      format.html { redirect_to my_names_url, notice: "My name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_name
      @my_name = MyName.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_name_params
      params.require(:my_name).permit(:name, :surname)
    end
end

demo-models/app/controllers/my_totals_controller.rb
class MyTotalsController < ApplicationController
  before_action :set_my_total, only: %i[ show edit update destroy ]

  # GET /my_totals or /my_totals.json
  def index
    @my_totals = MyTotal.all
  end

  # GET /my_totals/1 or /my_totals/1.json
  def show
  end

  # GET /my_totals/new
  def new
    @my_total = MyTotal.new
  end

  # GET /my_totals/1/edit
  def edit
  end

  # POST /my_totals or /my_totals.json
  def create
    @my_total = MyTotal.new(my_total_params)

    respond_to do |format|
      if @my_total.save
        format.html { redirect_to @my_total, notice: "My total was successfully created." }
        format.json { render :show, status: :created, location: @my_total }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_totals/1 or /my_totals/1.json
  def update
    respond_to do |format|
      if @my_total.update(my_total_params)
        format.html { redirect_to @my_total, notice: "My total was successfully updated." }
        format.json { render :show, status: :ok, location: @my_total }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_totals/1 or /my_totals/1.json
  def destroy
    @my_total.destroy
    respond_to do |format|
      format.html { redirect_to my_totals_url, notice: "My total was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_total
      @my_total = MyTotal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_total_params
      params.require(:my_total).permit(:first_operator, :second_operator, :total)
    end
end

demo-models/app/helpers/application_helper.rb
module ApplicationHelper
end

demo-models/app/helpers/my_names_helper.rb
module MyNamesHelper
end

demo-models/app/helpers/my_totals_helper.rb
module MyTotalsHelper
end

demo-models/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoModels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

demo-models/app/views/my_names/_form.html.erb
<%= form_with(model: my_name) do |form| %>
  <% if my_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_name.errors.count, "error") %> prohibited this my_name from being saved:</h2>

      <ul>
        <% my_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

demo-models/app/views/my_names/edit.html.erb
<h1>Editing My Name</h1>

<%= render 'form', my_name: @my_name %>

<%= link_to 'Show', @my_name %> |
<%= link_to 'Back', my_names_path %>

demo-models/app/views/my_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Names</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Denominazione</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_names.each do |my_name| %>
      <tr>
        <td><%= my_name.name %></td>
        <td><%= my_name.surname %></td>
        <td><%= my_name.name_and_surname %></td>
        <td><%= link_to 'Show', my_name %></td>
        <td><%= link_to 'Edit', edit_my_name_path(my_name) %></td>
        <td><%= link_to 'Destroy', my_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Name', new_my_name_path %>

demo-models/app/views/my_names/new.html.erb
<h1>New My Name</h1>

<%= render 'form', my_name: @my_name %>

<%= link_to 'Back', my_names_path %>

demo-models/app/views/my_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @my_name.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @my_name.surname %>
</p>

<p>
<strong>Name and Surname:</strong>
<%= @my_name.name_and_surname %>
</p>

<%= link_to 'Edit', edit_my_name_path(@my_name) %> |
<%= link_to 'Back', my_names_path %>

demo-models/app/views/my_totals/_form.html.erb
<%= form_with(model: my_total) do |form| %>
  <% if my_total.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_total.errors.count, "error") %> prohibited this my_total from being saved:</h2>

      <ul>
        <% my_total.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_operator %>
    <%= form.number_field :first_operator %>
  </div>

  <div class="field">
    <%= form.label :second_operator %>
    <%= form.number_field :second_operator %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

demo-models/app/views/my_totals/edit.html.erb
<h1>Editing My Total</h1>

<%= render 'form', my_total: @my_total %>

<%= link_to 'Show', @my_total %> |
<%= link_to 'Back', my_totals_path %>

demo-models/app/views/my_totals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Totals</h1>

<table>
  <thead>
    <tr>
      <th>First operator</th>
      <th>Second operator</th>
      <th>Total</th>
      <th>half total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_totals.each do |my_total| %>
      <tr>
        <td><%= my_total.first_operator %></td>
        <td><%= my_total.second_operator %></td>
        <td><%= my_total.total %></td>
        <td><%= my_total.half_total %></td>
        <td><%= link_to 'Show', my_total %></td>
        <td><%= link_to 'Edit', edit_my_total_path(my_total) %></td>
        <td><%= link_to 'Destroy', my_total, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Total', new_my_total_path %>

demo-models/app/views/my_totals/new.html.erb
<h1>New My Total</h1>

<%= render 'form', my_total: @my_total %>

<%= link_to 'Back', my_totals_path %>

demo-models/app/views/my_totals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First operator:</strong>
  <%= @my_total.first_operator %>
</p>

<p>
  <strong>Second operator:</strong>
  <%= @my_total.second_operator %>
</p>

<p>
  <strong>Total:</strong>
  <%= @my_total.total %>
</p>

<%= link_to 'Edit', edit_my_total_path(@my_total) %> |
<%= link_to 'Back', my_totals_path %>